### ISSUE TITLE
Constructor parameters?

### ISSUE THREAD

**Issue by jcowking** [mperdeck/Common.Logging.Log4Net.Universal#1]
Hi
I am trying to use the Common.Logging.Log4Net.Univeral to get everything talking to the latest version of Log4Net - currently 2.0.7

\<factoryAdapter type="Common.Logging.Log4Net.Universal.Log4NetFactoryAdapter, Common.Logging.Log4Net.Universal"/>

I've noticed from the Common.Logging.Log4Net.Universal source code (and errors!) that the new factory adapter does not take any constructor arguments.

My previous setting here was like this:
\<factoryAdapter type="Common.Logging.Log4Net.Universal.Log4NetFactoryAdapter, Common.Logging.Log4Net1215">
          \<arg key="configType" value="INLINE"/>
          \<arg key="level" value="ALL" />
\</factoryAdapter>

So, previously, I would then detail the log4net settings in the same config file.

Now that the Universal adapter takes no parameters, I'm unable to get any logging happening.  The inline log4net config isn't picked up.

Does anyone know how I can tell the new adapter where to get its logging config from?  

Julian

**Comment by mwinkler** [comment]
I have the same issue?
Is there any documentation how to configure for inline usage?

**Comment by jcowking** [comment]
Hi there


I never received any replies despite numerous venues of enquiry.  However I can report I found success with a bit of trial an error.


The trick for me was to continue to use the exact configuration as before (when using the Common.Logging.log4net1215, for example) and then, adding a <runtime /> ....<bindingRedirect  /> entry to point to the new version of log4net i was using (in my case 2.08).


I'll have access to my work computer tomorrow if you need further/more specific details.


Thanks,

Julian


________________________________

**Comment by mperdeck** [comment]
Sorry for the late reply.

As jcowking points out, you can use any Log4Net adapter you want. JSNLog simply talks to the Common.Logging interface, and doesn't care what adapter sits behind that. The only reason I introduced Common.Logging.Log4Net.Universal.Log4NetFactoryAdapter is that the official Common.Logging.Log4Net.Log4NetFactoryAdapter doesn't support Log4Net versions higher than 2.0.5.

Regarding the lack of the configType and level parameters:
Common.Logging.Log4Net.Universal.Log4NetFactoryAdapter doesn't attempt to configure log4net in any way, so doesn't need these parameters. You should be able to for example configure Log4Net with the <log4net> element in your web.config file as has been done in the demo projects. For example:
https://github.com/mperdeck/jsnlogSimpleWorkingDemos/blob/master/jsnlogSimpleWorkingDemos/JSNLogDemo_Log4Net_RequestIds/Web.config
