### ISSUE TITLE
GlobalVariablesContext not working with AdoNetAppender

### ISSUE THREAD

**Issue by queston02** [mperdeck/Common.Logging.Log4Net.Universal#3]
HI,

Before using Log4Net.Universal we were using Logging.Log4net1213 and in that we were using custom properties for passing values to the AdoNetAppender. This used to work perfectly. But now since we have changed to Log4Net.Universal we started using GlobalVariablesContext.Set(..) for passing values to the AdoNetAppender because CustomProperties doesn't exist. Unfortunately now those values are coming as null and throwing up error during logging. There is also no documentation that i am aware of for Log4Net.Universal. Please let me know how to fix this.

Previuos Version :- Common.Logging, Version=2.2.0.1, Common.Logging.Log4Net1213
Current Version :- Version=3.3.1.0 Common.Logging.Core, Common.Logging & Common.Logging.Log4Net.Universal.1.0.1

Thanks,
Queston02

**Comment by mperdeck** [comment]
I'm not quite sure what you're setting out to achieve. However, this is an open source project. Please have a look at the sources. You'll find it is a very simple. If you decide to make improvements that would have value for all users, I would be open to a pull request.

**Comment by queston02** [comment]
Just wanted to let you know that original Log4Net1213 have below mentioned piece of code through which custom properties set in ILog of common.logging were passed to log4net.
			`if (base.CustomProperties != null && base.CustomProperties.Count > 0)
			{
				foreach (KeyValuePair<string, object> customProperty in base.CustomProperties)
				{
					ThreadContext.get_Properties().set_Item(customProperty.Key, customProperty.Value);
				}
			}`
This is missing in your Log4Net.Universal.

**Comment by PokeyTheCat** [comment]
@queston02 I think I'm starting to understand what you're getting at. With this package you can't pass anything to the log4net.ThreadContext, is that snippet from your own code? Couldn't you just override and use the ``Log4NetThreadVariablesContext``.

Copy ``Log4NetGlobalVariablsContext.cs``, ``Log4NetThreadVariablesContext.cs``,``Log4NetNestedThreadVariablesContext.cs``, etc over and then put following in the ``Log4NetLogger.cs``:
```C#
/// <summary>
/// Returns the global context for variables
/// </summary>
public override IVariablesContext GlobalVariablesContext
{
	get { return new Log4NetGlobalVariablesContext(); }
}

/// <summary>
/// Returns the thread-specific context for variables
/// </summary>
public override IVariablesContext ThreadVariablesContext
{
	get { return new Log4NetThreadVariablesContext(); }
}

/// <summary>
/// 
/// </summary>
public override INestedVariablesContext NestedThreadVariablesContext
{
	get { return new Log4NetNestedThreadVariablesContext(); }
}
```

**Comment by queston02** [comment]
@PokeyTheCat that makes complete sense. Thanks for the suggestion. If things workout i might even put a pull request with changes.
