### ISSUE TITLE
Add support for .NET4.5

### ISSUE THREAD

**Issue by Klezer** [mperdeck/Common.Logging.Log4Net.Universal#5]
Can you add support for .NET 4.5.1?
For the moment the lowest supported version is .NET 4.6.1
Because of this, I can not use this package in my project, which is at version 4.5.1

**Comment by mperdeck** [comment]
.Net 4.5.1 was superseded by 4.5.2 back in 2014. Support ended last year. 4.6.1 itself was superseded last year. Why not upgrade your application to 4.6.1 or later?

**Comment by Klezer** [comment]
That is what I did in the meantime. You can close this issue.
